FROM nvidia/cuda:12.6.2-runtime-ubuntu22.04

# Install Python and ComfyUI dependencies
RUN apt-get update && apt-get install -y \
    git \
    python3 \
    python3-pip \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && apt-get clean

# Clone and set up ComfyUI
WORKDIR /app
RUN git clone https://github.com/comfyanonymous/ComfyUI.git
WORKDIR /app/ComfyUI
RUN pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu124
RUN pip install -U xformers==0.0.28.post3 --index-url https://download.pytorch.org/whl/cu124
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 8188
EXPOSE 8188

# Set entrypoint with required arguments
ENTRYPOINT ["python3", "/app/ComfyUI/main.py", "--listen", "0.0.0.0", "--port", "8188"]